name: Deploy Strapi to ECS Blue/Green

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'pratyush_nigel_baxla'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set variables
        run: |
          IMAGE="301782007642.dkr.ecr.ap-south-1.amazonaws.com/pratyush_baxla/strapi-app:${{ github.event.inputs.image_tag }}"
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV
          echo "Using image: $IMAGE"
          echo "CODEDEPLOY_APP=pratyush-strapi" >> $GITHUB_ENV
          echo "CODEDEPLOY_DG=pratyush-strapi-dg" >> $GITHUB_ENV

      - name: Debug image URI
        run: |
          echo "IMAGE_URI=$IMAGE_URI"

      - name: Render ECS task definition
        env:
          IMAGE: 301782007642.dkr.ecr.ap-south-1.amazonaws.com/pratyush_baxla/strapi:${{ github.event.inputs.image_tag }}

          STRAPI_APP_KEYS: ${{ secrets.STRAPI_APP_KEYS }}
          STRAPI_API_TOKEN_SALT: ${{ secrets.STRAPI_API_TOKEN_SALT }}
          STRAPI_ADMIN_JWT_SECRET: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          STRAPI_TRANSFER_TOKEN_SALT: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
          STRAPI_ENCRYPTION_KEY: ${{ secrets.STRAPI_ENCRYPTION_KEY }}

          STRAPI_JWT_SECRET: ${{ secrets.STRAPI_JWT_SECRET }}
          STRAPI_DATABASE_PASSWORD: ${{ secrets.STRAPI_DATABASE_PASSWORD }}
        run: |
          envsubst < taskdef.json > taskdef_rendered.json

      - name: Verify rendered task definition
        run: |
          cat taskdef_rendered.json

      - name: Register ECS task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://taskdef_rendered.json

      - name: Render AppSpec
        run: |
          sed "s|<TASK_DEFINITION_ARN>|$TASK_DEF_ARN|" appspec.yaml > appspec_rendered.yaml

      - name: Create CodeDeploy revision file
        run: |
          jq -Rs '{
          revisionType: "AppSpecContent",
          appSpecContent: {
          content: .
            }
          }' appspec_rendered.yaml > revision.json

      - name: Debug revision file
        run: |
          cat revision.json

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP \
            --deployment-group-name $CODEDEPLOY_DG \
            --revision file://revision.json \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes
