name: Deploy Strapi to ECS Blue/Green

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'pratyush_nigel_baxla'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set variables
        run: |
          IMAGE="301782007642.dkr.ecr.ap-south-1.amazonaws.com/pratyush_baxla/strapi-app:${{ github.event.inputs.image_tag }}"
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV
          echo "Using image: $IMAGE"
          echo "CODEDEPLOY_APP=pratyush-strapi" >> $GITHUB_ENV
          echo "CODEDEPLOY_DG=pratyush-strapi-dg" >> $GITHUB_ENV

      - name: Debug image URI
        run: |
          echo "IMAGE_URI=$IMAGE_URI"

      - name: Render task definition
        run: |
          sed "s|<IMAGE_URI>|$IMAGE_URI|" taskdef.json > taskdef_rendered.json

      - name: Verify rendered task definition
        run: |
          cat taskdef_rendered.json

      - name: Register ECS task definition
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef_rendered.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Render AppSpec
        run: |
          sed "s|<TASK_DEFINITION_ARN>|$TASK_DEF_ARN|" appspec.yaml > appspec_rendered.yaml

      - name: Create CodeDeploy revision file
        run: |
          cat <<EOF > revision.json
          {
              "revisionType": "AppSpecContent",
              "appSpecContent": {
              "content": "$(sed 's/"/\\"/g' appspec_rendered.yaml)"
              }
          }
          EOF

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP \
            --deployment-group-name $CODEDEPLOY_DG \
            --revision file://revision.json \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes
